name: ci

on:
  push:
    branches:
      - develop
      - rc
      - stable
  pull_request:
    branches:
      - develop
      - rc
      - stable

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: yarn

      - name: preparing .env ⏚
        run: cp .env.example .env

      - name: install dependencies 🎁
        run: yarn --frozen-lockfile

      - name: build gen
        run: yarn build:gen

      - name: type check ⚙️
        run: yarn nuxi typecheck

      - name: Run linter 👀
        run: yarn lint

      - name: Test build 👀
        run: yarn build
